apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application-deployment.yml
  - namespace.yaml
  - application-service.yml

namespace: test-namespace

commonLabels:
  app: application
