apiVersion: v1
kind: Service
metadata:
  name: microservice-app
  namespace: test-namespace
spec:
  type: ClusterIP
  ports:
    - name: 'application-microservice'
      port: 3000
      targetPort: 3000
  selector:
    app: microservice-app
